-- Agent archetypes — base prompts will be refined during Phase 4
INSERT INTO agent_archetypes (role_name, display_name, system_prompt, tools, max_tokens, temperature, human_gate, memory_categories) VALUES
('opportunity_analyst', 'Opportunity Analyst', 'You analyze federal solicitations. Extract requirements, evaluation criteria, compliance conditions, and risk flags. Be thorough and precise.', ARRAY['memory_search','memory_write','opportunity_details','emit_event'], 4096, 0.2, false, ARRAY['requirements','agency_patterns']),
('scoring_strategist', 'Scoring Strategist', 'You evaluate opportunity fit for specific companies. Score based on capabilities match, past performance, and competitive positioning.', ARRAY['memory_search','memory_write','tenant_profile','library_search','score_adjust'], 3072, 0.3, false, ARRAY['scoring_calibration','agency_fit']),
('capture_strategist', 'Capture Strategist', 'You recommend pursuit decisions and develop win strategies. Analyze competitive landscape and identify differentiators.', ARRAY['memory_search','memory_write','tenant_profile','library_search','opportunity_details','proposal_read'], 8192, 0.4, true, ARRAY['strategy','competitive_intel']),
('proposal_architect', 'Proposal Architect', 'You design proposal outlines and map content to requirements. Structure sections for maximum evaluation score.', ARRAY['memory_search','memory_write','tenant_profile','library_search','opportunity_details','section_draft','compliance_flag'], 8192, 0.3, true, ARRAY['outline_patterns','section_structure']),
('section_drafter', 'Section Drafter', 'You draft proposal sections using library content and requirements. Match the customers writing style and preferences.', ARRAY['memory_search','memory_write','library_search','proposal_read','opportunity_details','section_draft','request_human_review'], 8192, 0.4, true, ARRAY['writing_style','content_preferences']),
('compliance_reviewer', 'Compliance Reviewer', 'You verify every RFP requirement is addressed in the proposal. Check format compliance, content coverage, and submission requirements.', ARRAY['memory_search','memory_write','proposal_read','opportunity_details','compliance_flag','review_comment'], 4096, 0.1, false, ARRAY['compliance_patterns','agency_interpretation']),
('color_team_reviewer', 'Color Team Reviewer', 'You simulate color team reviews. Score against evaluation criteria, identify strengths and weaknesses, recommend revisions.', ARRAY['memory_search','memory_write','proposal_read','opportunity_details','review_comment'], 8192, 0.3, true, ARRAY['review_calibration','reviewer_patterns']),
('partner_coordinator', 'Partner Coordinator', 'You manage partner communications and track deliverables. Draft reminders and status reports.', ARRAY['memory_search','memory_write','proposal_read','notify','emit_event'], 2048, 0.3, true, ARRAY['partner_reliability','communication_patterns']),
('librarian', 'Librarian', 'You catalog, score, and maintain the content library. Decompose documents into atomic units, tag with categories, and track quality.', ARRAY['memory_search','memory_write','library_search','emit_event'], 4096, 0.2, false, ARRAY['content_quality','categorization']),
('packaging_specialist', 'Packaging Specialist', 'You compile and format final submission packages. Verify format requirements and generate submission checklists.', ARRAY['memory_search','memory_write','proposal_read','opportunity_details','compliance_flag','emit_event'], 4096, 0.1, true, ARRAY['format_requirements','agency_portal_quirks'])
ON CONFLICT (role_name) DO NOTHING;
