import type { SeedPage } from './types';

/** /engine — hero + 6-step process + 3 differentiators + CTA. Accent: hero "Win" = award. */
export const engine: SeedPage = {
  pageKey: 'engine',
  title: 'Engine',
  blocks: [
    {
      section: 'hero',
      displayOrder: 0,
      excerpt: 'The Engine',
      title: 'Expert + AI + Process = *Win*.',
      body: 'RFP Pipeline is not just software and not just a consultant. It is a structured system where expert curation, isolated AI, and stage-gated workflows work together at every step of the proposal lifecycle.',
      metadata: { accent: 'award' },
    },
    {
      section: 'steps_header',
      displayOrder: 1,
      title: 'How It Works',
      metadata: {},
    },
    {
      section: 'steps',
      displayOrder: 2,
      title: 'Source Scout Finds',
      body: 'Automated monitoring scans SAM.gov, SBIR.gov, DSIP, and agency portals daily. New solicitations, amendments, and deadline changes are captured and queued for expert review.',
      excerpt: 'No opportunity slips through the cracks. Source Scout runs on a schedule, compares page snapshots, and flags meaningful changes using Claude classification.',
      metadata: { number: '01' },
    },
    {
      section: 'steps',
      displayOrder: 3,
      title: 'Expert Curates',
      body: 'Every solicitation is reviewed by Eric Wagner — 25 years of federal R&D experience. Topics are scored, compliance requirements are extracted, and volumes are structured before anything reaches your feed.',
      excerpt: 'This is not a raw data dump. Every opportunity in your pipeline has been human-verified, annotated with expert notes, and structured for proposal development.',
      metadata: { number: '02' },
    },
    {
      section: 'steps',
      displayOrder: 4,
      title: 'AI Structures',
      body: 'Once curated, AI agents extract compliance matrices, map required sections, identify page limits and formatting rules, and build proposal outlines automatically.',
      excerpt: 'Your isolated AI team works only with your data. No cross-contamination between tenants. The compliance engine catches requirements that humans miss.',
      metadata: { number: '03' },
    },
    {
      section: 'steps',
      displayOrder: 5,
      title: 'Customer Writes',
      body: 'You and your team fill in the proposal using the structured workspace. The content library suggests proven atoms from your past proposals. Section-level collaboration keeps everyone focused.',
      excerpt: 'Stage-gated progression ensures quality: draft, review, finalize. Role-based access means your PI sees their sections, your contracts person sees theirs, and external partners see only what you share.',
      metadata: { number: '04' },
    },
    {
      section: 'steps',
      displayOrder: 6,
      title: 'AI Assists',
      body: 'AI agents draft sections using your content library, the solicitation requirements, and the compliance matrix. Every draft is clearly marked and requires human review.',
      excerpt: 'The AI does not submit for you. It drafts. You review, edit, accept, or reject. The compliance engine checks every section against the requirements matrix in real time.',
      metadata: { number: '05' },
    },
    {
      section: 'steps',
      displayOrder: 7,
      title: 'Expert Reviews',
      body: 'Before submission, your proposal goes through a structured review process. Compliance checks, page counts, formatting verification, and expert feedback ensure submission readiness.',
      excerpt: 'The gold team review is where proposals go from good to winning. Our system tracks every requirement, every page limit, and every formatting rule so nothing is missed.',
      metadata: { number: '06' },
    },
    {
      section: 'differentiators_header',
      displayOrder: 8,
      title: 'Why This Model Works',
      metadata: {},
    },
    {
      section: 'differentiators',
      displayOrder: 9,
      excerpt: 'Isolation',
      title: 'Your Data. Your AI.',
      body: 'Every tenant gets isolated AI agents that only see their data. No shared context windows, no cross-contamination, no data leakage between companies.',
      metadata: {},
    },
    {
      section: 'differentiators',
      displayOrder: 10,
      excerpt: 'Accountability',
      title: 'Human in the Loop.',
      body: 'Every AI output is clearly marked and requires human review. Every solicitation is expert-curated. Every submission decision is yours.',
      metadata: {},
    },
    {
      section: 'differentiators',
      displayOrder: 11,
      excerpt: 'Structure',
      title: 'Stage-Gated Quality.',
      body: 'Proposals progress through defined stages with compliance checks at every gate. No shortcutting the review process. No submitting without verification.',
      metadata: {},
    },
    {
      section: 'cta',
      displayOrder: 12,
      title: 'See the engine in action.',
      body: 'Join the founding cohort and experience the full workflow.',
      metadata: { ctaLabel: 'Apply Now', ctaHref: '/apply' },
    },
  ],
};
