#!/usr/bin/env node
/**
 * write-ui-docs.mjs — regenerate `docs/UI_ATLAS.md` and `docs/UI_STATES.md` from the run indexes.
 *
 * ── WHY THIS EXISTS ──────────────────────────────────────────────────────────────────────────
 * Both docs opened with *"Regenerate; do not hand-edit"* and **nothing regenerated them**. They were
 * transcribed by hand after a run, so every count drifted the moment the next run landed — and the
 * per-state table, 300-odd rows of image filenames, pointed at files a re-run had renumbered out of
 * existence. A reader following one found nothing, which is worse than a doc that admits it is old.
 *
 * The numbers in both files are pure functions of `index.json`, `sheets.json` and `responsive.json`.
 * So they are computed here, and the prose that is genuinely written by a person stays in this
 * script — the same shape as `catalog-ui.mjs`, which builds `docs/UI_CATALOG.md` the same way.
 *
 * It also PRUNES: any `.jpg`/`.png` in `docs/ui-states/` that no index references is deleted, so the
 * directory holds this run's evidence and nothing else. A stale screenshot beside a fresh one is
 * indistinguishable from it.
 *
 *   cd frontend && node scripts/write-ui-docs.mjs [--prune]
 *
 * Exit 0 · 2 if an index is missing (run the capture first — a doc written from no data is a lie
 * with a table in it).
 */
import fs from 'node:fs';
import path from 'node:path';

const REPO = '/home/user/govwin';
const ATLAS = path.join(REPO, 'docs/ui-atlas');
const STATES = path.join(REPO, 'docs/ui-states');
const PRUNE = process.argv.includes('--prune');

function readJson(p, what) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch {
    console.error(`✗ cannot read ${what} (${path.relative(REPO, p)}) — run the capture first`);
    process.exit(2);
  }
}

const atlas = readJson(path.join(ATLAS, 'index.json'), 'the atlas index');
const atlasSheets = readJson(path.join(ATLAS, 'sheets.json'), 'the atlas sheets');
const states = readJson(path.join(STATES, 'index.json'), 'the states index');
const stateSheets = readJson(path.join(STATES, 'sheets.json'), 'the states sheets');
const responsive = readJson(path.join(STATES, 'responsive.json'), 'the responsive index');
/**
 * The dense-state phone probe writes its OWN index rather than appending to `responsive.json`.
 *
 * Two writers on one file is how the second one's entries quietly vanish: `drive-ui-responsive.mjs`
 * rewrites `responsive.json` whole on every run, so anything the probe had merged in would be gone
 * the next time the responsive pass ran — and the images would then read as orphans that never
 * existed. Missing on disk is `{shots:[]}`, which is honest: the probe has not been run here.
 */
const projectMobile = readJson(path.join(STATES, 'project-mobile.json'), 'the project-mobile index');

const count = (rows, key) => rows.reduce((m, r) => (m[r[key]] = (m[r[key]] ?? 0) + 1, m), {});
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');

// ── docs/UI_ATLAS.md ─────────────────────────────────────────────────────────────────────────
const LANE_LABEL = {
  anon: 'public · no session',
  tenant: 'tenant_admin @ foundation',
  tenant2: 'tenant_admin @ immobileyes',
  admin: 'master_admin',
  partner: 'partner_admin @ entrepreneurs-center',
  collab: 'partner_user (collaborator)',
};
const byLane = count(atlas.shots, 'lane');
const broken = atlas.shots.filter((s) => s.errors?.length || s.boundary);
const A = [];
A.push('# UI ATLAS — every path, photographed');
A.push('');
A.push('> Images and `index.json` are generated by `frontend/scripts/capture-ui-atlas.mjs` +');
A.push('> `build-ui-contact-sheets.mjs`; **this prose is generated by `scripts/write-ui-docs.mjs`**');
A.push('> from those indexes. Do not hand-edit — re-run it.');
A.push('>');
A.push('> ⚠️ `--lane X` refreshes ONE lane and MERGES into `index.json`, keeping the other lanes\' shots');
A.push('> and the full-run coverage scalars, and stamping `partialLanes`. It used to REPLACE the file,');
A.push('> which silently cut `drive-ui-states.mjs` — which reads this index to decide what to drive —');
A.push('> down to a single lane. That drive now refuses a lane-partial index outright.');
A.push('>');
A.push('> **What is committed:** everything — the contact sheets, `index.json`, AND the per-route');
A.push('> full-page images, deliberately (see the note in `.gitignore`): they are the reviewable');
A.push('> record of what every screen actually looked like. That record is large — `docs/ui-atlas/`');
A.push('> is ~100MB of PNG and `docs/ui-states/` ~38MB of JPEG — so a re-run rewrites a lot of');
A.push('> bytes. Regenerate with:');
A.push('>');
A.push('> ```bash');
A.push('> cd frontend && node scripts/capture-ui-atlas.mjs && node scripts/build-ui-contact-sheets.mjs \\');
A.push('>   && node scripts/write-ui-docs.mjs');
A.push('> ```');
A.push('');
A.push(`**${atlas.shots.length} screenshots · ${atlas.reached} of ${atlas.considered} routes reached · `
  + `${broken.length} broken.** Every route is driven as the actor who owns it, at 1440×900, full page. `
  + 'The caption on each contact sheet carries what a picture cannot: HTTP status, rendered text length, '
  + 'and the button/link/input/form counts **counted in the live DOM** — so a page that looks full but '
  + 'built nothing is visible as such.');
if (atlas.partialLanes?.length) {
  A.push('');
  A.push(`⚠️ Lane(s) **${atlas.partialLanes.join(', ')}** were refreshed on their own; every other lane's `
    + 'shots are carried forward from the last full run.');
}
A.push('');
A.push('## Contact sheets — start here');
A.push('');
A.push('| sheet | lane | routes |');
A.push('|---|---|---:|');
for (const s of atlasSheets) A.push(`| \`${s.file}\` | ${s.lane} | ${s.routes.length} |`);
A.push('');
A.push('## Lanes');
A.push('');
A.push('| lane | actor | screenshots |');
A.push('|---|---|---:|');
for (const [lane, n] of Object.entries(byLane)) A.push(`| ${lane} | ${LANE_LABEL[lane] ?? '—'} | ${n} |`);
A.push('');
if (broken.length) {
  A.push('## Broken');
  A.push('');
  A.push('| lane | route | what |');
  A.push('|---|---|---|');
  for (const s of broken) A.push(`| ${s.lane} | \`${esc(s.route)}\` | ${esc(s.errors?.join(' · ') || 'error boundary rendered')} |`);
  A.push('');
}
A.push('## Every route, as photographed');
A.push('');
A.push('| lane | route | status | text | b/l/i/f | image |');
A.push('|---|---|---:|---:|---|---|');
for (const s of atlas.shots) {
  const r = s.rendered ?? {};
  A.push(`| ${s.lane} | \`${esc(s.route)}\`${s.redirected ? ` → \`${esc(s.finalUrl)}\`` : ''} | ${s.status} `
    + `| ${r.text ?? '—'} | ${r.buttons ?? 0}/${r.links ?? 0}/${r.inputs ?? 0}/${r.forms ?? 0} | \`${s.file}\` |`);
}
A.push('');
const unbound = Object.entries(atlas.unbound ?? {});
A.push('## Routes no lane could address');
A.push('');
if (!unbound.length && !(atlas.noLane ?? []).length) {
  A.push('None — every route in the catalog was reached by the actor who owns it.');
} else {
  for (const [route, why] of unbound) A.push(`- \`${route}\` — ${Array.isArray(why) ? why.join(' · ') : why}`);
  for (const route of atlas.noLane ?? []) A.push(`- \`${route}\` — no actor for its lane`);
}
A.push('');
fs.writeFileSync(path.join(REPO, 'docs/UI_ATLAS.md'), `${A.join('\n')}\n`);

// ── docs/UI_STATES.md ────────────────────────────────────────────────────────────────────────
const KIND_WHAT = {
  panel: 'a tab, filter, expander or card selection that replaced the main panel',
  open: 'an overlay as it first appears',
  toast: 'whatever the toast bus published',
  filled: 'every field populated (never submitted — that would be a create)',
  validation: 'the primary submit pressed with the form EMPTY',
  confirm: 'a native confirm()/prompt() intercepted, recorded and DISMISSED',
  stuck: '**an overlay that would NOT close — a defect**',
};
const byKind = Object.entries(count(states.shots, 'kind')).sort((a, b) => b[1] - a[1]);
const stateLanes = count(states.shots, 'lane');
const S = [];
S.push('# UI STATES — every modal, panel, form, confirm and toast');
S.push('');
S.push('> Images and `index.json` are generated by `drive-ui-states.mjs` + `drive-ui-responsive.mjs` +');
S.push('> `build-ui-contact-sheets.mjs --states`; **this prose is generated by');
S.push('> `scripts/write-ui-docs.mjs`** from those indexes. Do not hand-edit — re-run it.');
S.push('>');
S.push('> ⚠️ The drive\'s scope is `docs/ui-atlas/index.json`. A lane with no routes there used to be');
S.push('> skipped **silently**, and one run finished `EXIT=0` having driven 29 routes in 1 lane while');
S.push('> the committed index held 123 across 5. A lane-partial index is now a HARNESS DEFECT (exit 2)');
S.push('> on a full run.');
S.push('>');
S.push('> ⚠️ This drive is **NOT read-only** — it prints its mutation footprint. `pg_dump` before,');
S.push('> `pg_restore` after.');
S.push('');
S.push('`docs/UI_ATLAS.md` photographs every page **at rest**. Almost nothing a customer does happens at');
S.push('rest — and most of it is not a modal either. A tab switches the panel, a filter re-queries the');
S.push('list, an expander reveals a row, a card selects and swaps the pane beside it.');
S.push('');
S.push('| state | captured | what it is |');
S.push('|---|---:|---|');
for (const [k, n] of byKind) S.push(`| \`${k}\` | ${n} | ${KIND_WHAT[k] ?? '—'} |`);
S.push(`| **total** | **${states.shots.length}** | across **${states.routesDriven} routes** driven, in `
  + `**${Object.keys(stateLanes).length} lanes** (${Object.entries(stateLanes).map(([l, n]) => `${l} ${n}`).join(' · ')}) |`);
S.push('');
S.push(`Plus **${responsive.shots.length}** viewport captures (phone 390 · tablet 820 · desktop 1440), `
  + 'including the mobile nav drawer as a real overlay — a state the desktop pass structurally cannot reach.');
S.push('');
if (states.findings?.length) {
  S.push('## Findings — reported, not swallowed');
  S.push('');
  S.push('A route the drive could not finish is **uncovered, not passing**.');
  S.push('');
  S.push('| lane | route | what |');
  S.push('|---|---|---|');
  for (const f of states.findings) S.push(`| ${f.lane} | \`${esc(f.route)}\` | ${esc(f.trigger ? `"${f.trigger}" — ` : '')}${esc(f.what)} |`);
  S.push('');
}
S.push('## Contact sheets — start here');
S.push('');
S.push('Sheets group by KIND, not by route: twenty validation messages side by side is what makes the');
S.push('odd one visible.');
S.push('');
S.push('| sheet | states |');
S.push('|---|---:|');
for (const s of stateSheets) S.push(`| \`${s.file}\` | ${s.routes.length} |`);
S.push('');
S.push('## Every state captured');
S.push('');
S.push('| kind | lane | route | trigger | image |');
S.push('|---|---|---|---|---|');
const order = Object.fromEntries(Object.keys(KIND_WHAT).map((k, i) => [k, i]));
for (const s of [...states.shots].sort((a, b) => (order[a.kind] ?? 9) - (order[b.kind] ?? 9)
  || a.route.localeCompare(b.route) || a.file.localeCompare(b.file))) {
  S.push(`| ${s.kind} | ${s.lane} | \`${esc(s.route)}\` | ${s.trigger ? `"${esc(s.trigger)}"` : '—'} | \`${s.file}\` |`);
}
S.push('');
const dialogs = states.shots.filter((s) => s.kind === 'confirm' && s.message);
if (dialogs.length) {
  S.push('## Native dialogs, verbatim');
  S.push('');
  S.push('Every one intercepted and **dismissed** — the drive never accepts a destructive confirm.');
  S.push('');
  S.push('| route | message |');
  S.push('|---|---|');
  const seen = new Set();
  for (const d of dialogs) {
    const key = `${d.route}|${d.message}`;
    if (seen.has(key)) continue;
    seen.add(key);
    S.push(`| \`${esc(d.route)}\` | ${esc(d.message)} |`);
  }
  S.push('');
}
S.push('## Viewport captures');
S.push('');
S.push('| lane | route | viewport | image |');
S.push('|---|---|---|---|');
for (const s of [...responsive.shots, ...(projectMobile.shots ?? [])]) {
  S.push(`| ${s.lane} | \`${esc(s.route)}\` | ${s.viewport}${/nav-open/.test(s.file) ? ' · **nav open**' : ''}${/-open\./.test(s.file) ? ' · **panels open**' : ''} | \`${s.file}\` |`);
}
S.push('');
fs.writeFileSync(path.join(REPO, 'docs/UI_STATES.md'), `${S.join('\n')}\n`);

console.log(`✓ docs/UI_ATLAS.md  — ${atlas.shots.length} shot(s) · ${atlasSheets.length} sheet(s) · ${broken.length} broken`);
console.log(`✓ docs/UI_STATES.md — ${states.shots.length} state(s) across ${states.routesDriven} route(s) `
  + `· ${stateSheets.length} sheet(s) · ${responsive.shots.length + (projectMobile.shots?.length ?? 0)} viewport(s) `
  + `· ${states.findings?.length ?? 0} finding(s)`);

// ── prune ────────────────────────────────────────────────────────────────────────────────────
// A screenshot no index references is evidence from a run that no longer exists, sitting in the same
// directory as evidence that does. They are indistinguishable by looking.
const referenced = new Set([...states.shots, ...responsive.shots, ...(projectMobile.shots ?? [])].map((s) => s.file)
  .concat(stateSheets.map((s) => s.file)));
const orphans = fs.readdirSync(STATES).filter((f) => /\.(jpg|png)$/.test(f) && !referenced.has(f));
if (!orphans.length) console.log('  no orphaned state images');
else if (!PRUNE) console.log(`  ⚠️  ${orphans.length} image(s) in docs/ui-states/ are referenced by NO index — re-run with --prune`);
else {
  for (const f of orphans) fs.unlinkSync(path.join(STATES, f));
  console.log(`  pruned ${orphans.length} orphaned state image(s)`);
}
